### ISSUE TITLE
2 typos in doc

### ISSUE THREAD

**Issue by RolandGautier** [sukria/Backup-Manager#112]
Hi,
I just read the documentation and found 2 small typos :

- Page 14, last line : "This method uses all of the configu**_ar_**tion keys of the ssh method"
- Page 24, last exemple : "# backup-manager --b**_n_**urn 20060312"

As you see, nothing very urgent ... ;=)

Now, i'll try to use this powerfull tool ...

Have a nice day,
Roland

**Comment by kissifrot** [comment]
Fixed, thanks :)
