### ISSUE TITLE
Global s3 support

### ISSUE THREAD

**Issue by NoxInmortus** [sukria/Backup-Manager#127]
Hello,

s3 support is great but it only works with Amazon. It could be great to have full s3 support and be able to connect to other s3 providers. I'm using Scaleway for example.

We would need to have some additional parameters to be able to change the following configurations :
```
host_base
bucket_location
```

Thanks

**Comment by JD-ISWT** [comment]
The question is quite old, but here is a solution for S3 uploading elsewhere than Amazon

https://gist.github.com/dcoppari/f3b5622b14a5f6447cfdd5e2b08e6f63

**Comment by NoxInmortus** [comment]
I do not use backupmanager anymore, but thanks for the tip
