### ISSUE TITLE
wiki link to docs is broken

### ISSUE THREAD

**Issue by johnschult** [sukria/Backup-Manager#13]
http://wiki.backup-manager.org/index.php/Main_Page#Documentation

**Comment by Toub** [comment]
What about migrating the old wiki here, so it can be updated and maintained?
https://web.archive.org/web/20091209054552/http://wiki.backup-manager.org/index.php/Main_Page

**Comment by cypriani** [comment]
@Toub: just did that. This issue should probably be closed now. See also #71.

**Comment by kissifrot** [comment]
Right, done :)
