### ISSUE TITLE
backup-manager.org is not functional

### ISSUE THREAD

**Issue by markmevans** [sukria/Backup-Manager#24]
In case you are unaware of it, the backup-manager.org domain now appears to be "parked" on sedo and all related URLs simply display a few backup related links not associated with your project.

[Screenshot 12:19:12 5:16 PM](https://f.cloud.github.com/assets/2829024/23492/14047286-4a43-11e2-950a-010ef771b294.png)

**Comment by Toub** [comment]
+1 for removing all references to http://www.backup-manager.org.

This domain name is not required.

**Comment by Alex131089** [comment]
2016-01-23, https://github.com/sukria/Backup-Manager : "Versatile yet easy to use command line backup tool for GNU/Linux. Suitable for desktop and servers. http://www.backup-manager.org/"

**Comment by kissifrot** [comment]
Ping @sukria ;)
