### ISSUE TITLE
"make install" creates paths starting with double-slash

### ISSUE THREAD

**Issue by iva2k** [sukria/Backup-Manager#34]
"make install" creates paths starting with double-slash, which should not be used unless it is a path on the network.

In the Makefile, there are paths combined from $(DESTDIR)/$(PREFIX) and other similar constructs. Defaults are set as:
DESTDIR?=
PREFIX?="/usr/local"
which results in paths beginning with "//usr/local/...", which is apparently not intended and wrong.

One fix I can suggest is to require DESTDIR to end with a slash (if not empty), and change all "$(DESTDIR)/$(" to "$(DESTDIR)$(".

**Comment by kissifrot** [comment]
Is this still valid with 0.7.11 release?
