### ISSUE TITLE
backup-manager didn't delete old backup files

### ISSUE THREAD

**Issue by MurzNN** [sukria/Backup-Manager#5]
Config file is:
export BM_REPOSITORY_ROOT="/backups/org/projects"
export BM_TEMP_DIR="/tmp"
export BM_REPOSITORY_SECURE="true"
export BM_REPOSITORY_USER="root"
export BM_REPOSITORY_GROUP="root"
export BM_REPOSITORY_CHMOD="770"
export BM_ARCHIVE_CHMOD="660"
export BM_ARCHIVE_TTL="10"
export BM_ARCHIVE_STRICTPURGE="false"
export BM_ARCHIVE_NICE_LEVEL="10"
export BM_ARCHIVE_METHOD="tarball-incremental"

export BM_TARBALL_NAMEFORMAT="short"
export BM_TARBALL_FILETYPE="tar.gz"
export BM_TARBALL_OVER_SSH="false"
export BM_TARBALL_DUMPSYMLINKS="false"

export BM_TARBALL_DIRECTORIES="/store/org/projects"

export BM_TARBALL_BLACKLIST="*/nobackup"
export BM_TARBALL_EXTRA_OPTIONS=""

export BM_TARBALLINC_MASTERDATETYPE="weekly"
export BM_TARBALLINC_MASTERDATEVALUE="5"

export BM_LOGGER="true"
export BM_LOGGER_FACILITY="user"
export BM_PRE_BACKUP_COMMAND=""
export BM_POST_BACKUP_COMMAND=""

It creates master and increment archives successfully, but don't remove files older that 10 days.
Version is 0.7.9-3 on Debian Squeeze.

What is wrong in config file?
How can I debug all the process? Adding "--verbose" didn't help, output is only:
When validating the configuration file /etc/backup-manager.conf, 4 warnings were found.

**Comment by webscreen** [comment]
Hi there,

i'm using the last version of backup-manager and i've got the same problem...

Backup-manager didn't delete old backup files by the FTP method.
All files are correctly deleted in the archives folder (BM_REPOSITORY_ROOT="/var/archives") but not on the remote FTP server.

I'm using the ftp method :
export BM_UPLOAD_FTP_SECURE="false"
export BM_UPLOAD_FTP_PASSIVE="true"
export BM_UPLOAD_FTP_TEST="false"
export BM_UPLOAD_FTP_USER="xxxxxxxxx.xxx.net"
export BM_UPLOAD_FTP_PASSWORD="xxxxxxxxxxx"
export BM_UPLOAD_FTP_HOSTS="xxxxxxxxxxx.net"
export BM_UPLOAD_FTP_PURGE="true"
export BM_UPLOAD_FTP_TTL="4"
export BM_UPLOAD_FTP_DESTINATION="/test/"

It creates master and increment archives successfully, but don't remove files older that 4 days.
Evertything else is correct, i've got 0 error adding "--verbose" didn't help.

What's wrong ?

Version is 0.7.10 on CentOS 6.

**Comment by chandon** [comment]
@webscreen this is because #91

**Comment by Vagrantin** [comment]
I'm also experiencing the issue on Debian Jessie with backup-manager 0.7.12-debian1, i have set 
export BM_ARCHIVE_TTL="5"
export BM_TARBALL_NAMEFORMAT="long"
And the clean up is not perform locally, does somebody manage to drill down this issue ?

**Comment by kissifrot** [comment]
@Vagrantin Could you try with latest version in `devel`  branch ?

**Comment by Vagrantin** [comment]
@kissifrot no, I have to look at that, but it will take me a bit of time has I guess it's not packaged for Debian :D 
Today my work around is to cron a backup-manager -p on a daily basis otherwise it doesn't clean up old backup.
