### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by llaumgui** [sukria/Backup-Manager#61]
Hi,

is it possible to do a new release with all evolution since 2010 ?

Thx

**Comment by kissifrot** [comment]
Hello, version 0.7.11 was just released, don't hesitate to test it (I had some merge issues which should be fixed)

**Comment by cypriani** [comment]
And version 0.7.12 has been released since then. Should this issue be left open for 0.7.13? ;-)

**Comment by kissifrot** [comment]
Well I didn't have much time lately, but 0.7.13 release should be out in a few days when I'll find the time to do it ;-)
