### ISSUE TITLE
Debian Update

### ISSUE THREAD

**Issue by skazhikadyadya** [sukria/Backup-Manager#63]
Hi, from Debian Repository I have 0.7.10.1-debian1 version installed. 

How I can update it to latest? 

I don't know how to disable "UPLOAD" option: when I write "export BM_UPLOAD_METHOD="none" script wait for "Insert CD-ROM Drive to continue". How I can resolve that problem? I don't have CD-ROM at my VDS. :)

**Comment by kissifrot** [comment]
Well if you use Debian Repository you will have for the repository to be updated.

For the BM_UPLOAD_METHOD it seems like a bug, I'll look it up.

**Comment by kissifrot** [comment]
If you run BM in debug mode (add --debug to the BM arguments), do you see "Running the burning methods" / "Running the upload methods" ?

**Comment by omgiafs** [comment]
Just clone this repo and install newest version.

**Comment by omgiafs** [comment]
sanitize.sh, line 258:
```
# Burning system
if [[ -n "$BM_BURNING" ]]; then
        case "$BM_BURNING" in 
            ""|"no"|"false"|"none")
                BM_BURNING_METHOD="none"
            ;;
        esac
fi    
```

**Comment by dkogan** [comment]
I intend to update the debian package in the next few weeks. If somebody else is working on this, please tell me.

**Comment by ivan1986** [comment]
build 0.7.11, use uupdate + fix bugs https://launchpad.net/~ivan1986/+archive/ubuntu/ppa
@dkogan it may be useful
unfortunately I did not know about the package started to support

**Comment by dkogan** [comment]
Hi. The new package for Debian is currently in review, with the sources in the same place as before:

http://anonscm.debian.org/cgit/collab-maint/backup-manager.git

Does your tree fix any new bugs? Did you update the Debian BTS? Thanks.

**Comment by skazhikadyadya** [comment]
Hi, thank you. Looks nice.

**Comment by cypriani** [comment]
backup-manager 0.7.12 has been in Debian for a while now, shouldn't this be closed?

**Comment by kissifrot** [comment]
Thats right
