### ISSUE TITLE
Patches: fix dead links

### ISSUE THREAD

**Issue by dkogan** [sukria/Backup-Manager#65]
Hi. Here's a git tree to clean up the links to the dead backup-manager.org website. Github is confused, so you don't get a pull request.

https://github.com/dkogan/Backup-Manager/tree/fix_dead_links

**Comment by kissifrot** [comment]
Did you try to merge it in devel branch ?

**Comment by dkogan** [comment]
The fix_dead_links branch is the devel branch + 2 patches. What are you seeing?

**Comment by kissifrot** [comment]
I was just curiois, as Github should have been correctly able to create a pull request.

**Comment by dkogan** [comment]
Oh, I see. It doesn't think that my tree is related to the upstream tree, even though it very clearly is. Plain git commands still work, as they always do, however.

**Comment by kissifrot** [comment]
Merged, thanks
