### ISSUE TITLE
Patches: fix purging of incremental archive while keeping the master

### ISSUE THREAD

**Issue by dkogan** [sukria/Backup-Manager#67]
A bug report was filed on the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784446

This describes backup-manager purging incremental archives while keeping the master, which makes the archive set incomplete. A fix is available in https://github.com/dkogan/Backup-Manager/tree/fix_overzealous_ttl_purge

This is the fix_overzealous_ttl_purge branch

**Comment by kissifrot** [comment]
Thanks, I'll look into it

**Comment by kissifrot** [comment]
Merged, thanks
