### ISSUE TITLE
Where can i found the implementation of incremental compression/decompression using LZMA

### ISSUE THREAD

**Issue by chfakht** [sukria/Backup-Manager#70]
Hi, i'm working on lzma and i want just the incremental compression/decompression that you have used in your application
Can you help me in this please

**Comment by kissifrot** [comment]
Well we just used the Unix/linuxes commands available for this.

Without a precise question I can't help you.

**Comment by chfakht** [comment]
The question is not really related to the backup manager but to exactly the LZMA Algorithm.
here's my situation

I'm using CAN BUS to flash the binary file from the HOST to the MCU.

In order to speed up the flashing process. I want to make incremental compression to separate files so to get much smaller size .However ,i want to decompress the file using incremental decompression, so that the first part is being decompressed and the other part are coming from the can bus.

**Comment by kissifrot** [comment]
Well I'm afraid you used the wrong place to ask then.
