### ISSUE TITLE
enable to save mysql

### ISSUE THREAD

**Issue by mrglobule** [sukria/Backup-Manager#86]
Hello,
i try to run backup-manager - v on debian, but i have this message:
```
Using method "mysql".
Using existing MySQL client configuration file: /root/.backup-manager_my.cnf
Unable to exec first piped command /usr/bin/nice -n 10 /usr/bin/mysqldump --defaults-extra-file=/root/.backup-manager_my.cnf --opt -ubackup -hlocalhost -P3306  information_schema; check /tmp/bm-command.ncLCYp
Unable to find /var/archives/mail2-mysql-information_schema.20161128.sql.bz2
Releasing lock
```
Would you mind to help me?

Sorry for my poor english.

**Comment by kissifrot** [comment]
What do you have in the /tmp/bm-command.ncLCYp file?

**Comment by mrglobule** [comment]
Hi kissifrot,
thanks for the answer,
the file is:
`mysqldump: Got error: 1044: Access denied for user 'backup'@'localhost' to database 'information_schema' when using LOCK TABLES`
It's a problem of right, i check that.
Thanks a lot.

**Comment by kissifrot** [comment]
By default, only root user has access to `information_schema`, make sure your `backup` user can lock information_schema's tables

**Comment by mrglobule** [comment]
Thanks kissifrot,
i try to run backup-manager -v with the root user in the config file, but i have the same error ?!?

**Comment by kissifrot** [comment]
Which version of MySQL are you using?

**Comment by mrglobule** [comment]
`mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3`

**Comment by kissifrot** [comment]
With MySQL you can't backup `information_schema` with other databases at the same time

**Comment by mrglobule** [comment]
thanks a lot, so icannot put:
`export BM_MYSQL_DATABASES="__ALL__"`
in the bakup-manager.conf, i had to list the database and it's ok.
Thanks a lot

**Comment by kissifrot** [comment]
You can also use the ``BM_MYSQL_SAFEDUMPS` option and set it to `false`, but at a _higher_ risk of missing data
