### ISSUE TITLE
Can't locate object method "add_key_filename"

### ISSUE THREAD

**Issue by Mircl0hav** [sukria/Backup-Manager#87]
`Can't locate object method "add_key_filename" via package "0" (perhaps you forgot to load "0"?) at //usr/local/bin/backup-manager-upload line 949.`

when i run backup-manager -v

**Comment by Mircl0hav** [comment]
backup-manager don't create a bucket, i create the bucket manualy and i solve my problem

**Comment by guitoun3** [comment]
I have the same issue. I tried with an existing bucket but I still have this issue.

I added code below on this file `/usr/local/bin/backup-manager-upload` to list available buckets and I can see my bucket. 
```
my $debug_buckets = $s3->buckets;
foreach my $bucket ( @{ $debug_buckets->{buckets} } ) {
  print_info "You have a bucket: " . $bucket->bucket . "\n";
}
```
