### ISSUE TITLE
Remote purge through scp not working

### ISSUE THREAD

**Issue by sbourdette** [sukria/Backup-Manager#97]
I have search for long time !

in file /usr/bin/backup-manager-upload
in sub ssh_clean_directory

Replace this line 
`my $cmd = "$ssh $ssh_options $user".'@'.$host." ls $location/*";`
with this 
`my $cmd = "$ssh $ssh_options $user".'@'.$host." 'ls $location/*'";`

Without the quote, local directory is listed instead of remote. I don't know why.

**Comment by sornbarang** [comment]
thanks

**Comment by sbourdette** [comment]
Any chance to merge it ? Or could I have write access to the repository ?

**Comment by kissifrot** [comment]
Fixed, thanks :)

**Comment by sbourdette** [comment]
Do you know when this package will be pushed on official ubuntu repository ?

**Comment by kissifrot** [comment]
Version 0.7.14 was released, I hope they will keep it up
